---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

notifications:
  email: false
  slack:
    secure: "SraTETiY/H8lTr4pxGy9cIX+xlxj7gqiYMEf0yR625WkPOlMjLJ4bTPPw9jaXj+WZDgBwQoetuAj1FozKIeQDdRR9PEUdruo1wztmWccKVJ9cXgpAIOWH6eynJ9AzL+JLwiT7AjneCPWaF4ZQUrwtLf+UhEvC/JifpWO/Z/V6QptFBLIrAKuUkYpyOtQBzyFYL0hSd7u8cLnMkWAp/Iowmgdt6GmBiOkHcsRTThJohfBqIc4755pYbD6NkC0Ge0wpLauf8lS8kbD/gvJvm1FJCry1M71QBbtJR6d273/kvivP78evWvnkUAzTFzWtOiTRMFjTHbQy7az3uiJ72KoEBwKIqtKva0MsmWJzzbPssMCkx/PQap1z4iDtz2pMkDCxA8fcWHyIgRw2L4+hJVxA7BIEDg6NuVCTqaqLytHKNx/R11+EI0sLYYiF+rvBMAZGxtggKn8epfIXMMhHPHoGdvnoepY5ZDL4scscnjFIN7UGGGSb2CA5PPalWkn6NuqWSbaiGfyDSyDp1SolVcIBzAy23O7yY2q8vAyVeAk7nDJZ5hEpScmVeaZjiNoVus58e0eeGStdX0xDgez1FqIzq8MrzD2ppd69sBguZNE1/yWYDeysbNpE0LOo3XDkeXmiQDbeCbn7j0azasuKfq9ddgtv0p61R1Mc2PJdSzycUU="

deploy:
  provider: npm
  email: me@tomasbasham.co.uk
  api_key:
    secure: "046J0pEIwqjgibd8dDU1n8IDAqDLCgtvNkmcT/7x1/ptZU103jeKOMvUHVzeMwVxtWxMIum4F3XEgqqPON1SRCu9DDu+apbGxebBz+F/18gugj+Y63PVGZhGvwwxCfdCpnDeAE3JDVKp8kDvdeIrA9muTD055/tnWSjJM+w8n3i9q/ohSAxV0f2EMyPeHXhxiOeHU2pYLSXUsOtUxS+Yg/xaoK3/sQs2yylqcu16LRuxfl9XbUieAV4C+lZDbpP2XHR22WrSk7T0pMNqSclz9kS67jraYnDtg1nXqMGuPHd78N8qSTci30M6rvxLWVbpSgjuCU73+d6GAkGzNrGaCRfuqU5rvs8eTG1GN8kH6no5gFOVVrbGbFOZXys0szho/7JJY1oQPenqI3FnauMs1kJo0D/uFl1tUOE08vSiRw9FzpH08mnCexG1dHmPfu8PXCGRXkJAMNTRZ2voUo7kG+X71RbgEyTg9xLAM829swtsvFznQId0/zmNhrTKF6a6TwQFnsZP2UcQxie8oVYPrgVu+RoTqyIg/1pRMW1+Rg7WIyfhA+TuoawNUYdn50m6nijL8t63AI2jdzUipTFFc5oG9VvXhGdGQ7boihb+7ZBFcCIeL9XWyqvUCtbAsDlmcYrBVJ1GcbdPllzYVHnOmrlVBkMNeAWcD7ugEWJ0Asw="
  on:
    tags: true
    repo: tomasbasham/ember-cli-persistence
